version: '3.8'

services:
  log-server:
    build: .
    ports:
      - "8015:8015"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=${DATABASE_PATH}
      - PORT=${PORT}
      - ACCOUNT_SECRET_KEYS=${ACCOUNT_SECRET_KEYS}
    volumes:
      - db-data:/app/data
      - ./sql:/app/sql
    restart: unless-stopped
    networks:
      - sbc-net

volumes:
  db-data:

networks:
  sbc-net:
    driver: bridge
    name: sbc-net
    external: true